databases:
  - name: postgres
    databaseName: postgres
    user: postgres
    plan: free

services:
  - type: web
    name: shoponline
    runtime: ruby
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "./bin/rails server"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: postgres
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: 2 # sensible default

  - type: worker
    name: sidekiq
    runtime: ruby
    buildCommand: bundle install; bundle exec rake assets:precompile; bundle exec rake assets:clean;
    startCommand: bundle exec puma -t 5:5 -p ${PORT:-3000} -e ${RACK_ENV:-development}
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: shoponline
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
