databases:
  - name: shoponline
    databaseName: shoponline
    user: shoponline
    plan: free

  services:
  - type: redis
    name: sidekiq-redis
    region: ohio
    maxmemoryPolicy: noeviction
    ipAllowList: [] # only allow internal connections

  - type: worker
    name: sidekiq-redis
    runtime: ruby
    region: ohio
    buildCommand: bundle install
    startCommand: bundle exec sidekiq
    envVars:
      - key: REDIS_URL
        fromService:
          type: redis
          name: sidekiq-redis
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
  - type: web
    name: shoponline
    runtime: ruby
    region: ohio
    buildCommand: "./bin/render-build.sh"
    startCommand: bundle exec puma -t 5:5 -p ${PORT:-3000} -e ${RACK_ENV:-development} ./bin/rails db:create  ./bin/rails db:migrate  ./bin/rails server  bin/rails tailwindcss:watch
    envVars:
      - key: DATABASE_URL
        fromDatabase: shoponline
      - key: REDIS_URL
        fromService:
          type: redis
          name: sidekiq-redis
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: 2
