databases:
  - name: shoponline
    databaseName: shoponline
    user: shoponline
    plan: free

services:
  - type: web
    name: shoponline
    runtime: ruby
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "./bin/rails db:create && ./bin/rails db:migrate && ./bin/rails server && bin/rails tailwindcss:watch"
    envVars:
      - key: DATABASE_URL
        value: postgres://shoponline:triT0sQ4JRS5a5KCVq4BY3DraMEuEb88@dpg-cn2j3s8cmk4c73dhipc0-a.oregon-postgres.render.com/shoponline_s91g
      - key: RAILS_MASTER_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: 2
      - key: REDIS_URL
        fromService:
          name: sidekiq-redis
          type: redis
          property: connectionString
  - type: redis
    name: sidekiq-redis
    region: ohio
    maxmemoryPolicy: noeviction
    ipAllowList: [] # only allow internal connections
  - type: worker
    name: sidekiq
    runtime: ruby
    buildCommand: bundle install; bundle exec rake assets:precompile; bundle exec rake assets:clean;
    startCommand: bundle exec puma -t 5:5 -p ${PORT:-3000} -e ${RACK_ENV:-development}
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: shoponline
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: REDIS_URL
        fromService:
          name: sidekiq-redis
          type: redis
          property: connectionString
